/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2026-10-04-7366b2f552-diffractor"
#endif /* AVUTIL_FFVERSION_H */
